# Generated by Django 5.0.1 on 2024-01-28 08:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0003_customuser_department'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysioSessionAdmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_no', models.CharField(max_length=255, unique=True)),
                ('date_of_visit', models.DateField()),
                ('discharge', models.BooleanField(default=False)),
                ('discharge_date', models.DateField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('more_notes', models.TextField()),
                ('patient_type', models.CharField(max_length=255)),
                ('clinic_master_admission_no', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity_of_sessions', models.PositiveIntegerField(default=0)),
                ('department', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='authentication.department')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis_physio_admission', to='patients.diagnosis')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_physio_admission', to='patients.patient')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ward', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.ward')),
            ],
        ),
        migrations.CreateModel(
            name='PhysioSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('physiosession_no', models.CharField(max_length=255)),
                ('more_notes', models.TextField()),
                ('quantity_of_session_left', models.CharField(max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('therapy', models.ManyToManyField(default='Old Therapy', to='patients.therapy')),
                ('admission_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='physio_admission_no', to='physio.physiosessionadmission')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50)),
                ('quantity_of_session', models.PositiveIntegerField()),
                ('invoice_date', models.DateField()),
                ('visit_no', models.CharField(max_length=255)),
                ('physiosessionadmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_physiosessionadmission', to='physio.physiosessionadmission')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_number', models.CharField(max_length=50, unique=True)),
                ('quantity_of_session', models.PositiveIntegerField()),
                ('visit_no', models.CharField(max_length=255)),
                ('payment_date', models.DateField()),
                ('physiosessionadmission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_physiosessionadmission', to='physio.physiosessionadmission')),
            ],
        ),
        migrations.CreateModel(
            name='RequestForInpatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_no', models.CharField(max_length=255)),
                ('patient_full_name', models.CharField(max_length=255)),
                ('request_body', models.TextField()),
                ('request_date', models.DateField(auto_now_add=True)),
                ('request_status', models.BooleanField(default=False)),
                ('request_to_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.department')),
            ],
        ),
        migrations.CreateModel(
            name='TotalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity_of_session', models.PositiveIntegerField()),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
