# Generated by Django 5.0.1 on 2024-01-29 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='first_name',
            new_name='firstname',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='surname',
            new_name='lastname',
        ),
    ]
