# Generated by Django 5.0.1 on 2024-02-03 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_rename_first_name_patient_firstname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='date_of_birth',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='patient_no',
            new_name='patientno',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='phone_number',
            new_name='phoneno',
        ),
    ]
